language: node_js
sudo: required
before_script:
  - npm install -g bower polylint web-component-tester
  - bower install
  - polylint
env:
  global:
    - secure: juAkt5bPEF2Wr4Rfmm6JIR18iNilFSSj+xF8YaRESzASpIU3gvc3pfKXfT3SotS83wrjAAuIeC8US01Cve/ynGLtMIq61b6yg6oN0sNras2WT4MoKAFKeezntvvX6Mi+bzlHimTB3vCC7whYtBjxiMCvZPRR31/ZE9NGK41wBDs=
    - secure: Ob/Jlx2PQbIrOVWqXfuOb4eGznaOAoqCe/PVvG3GSbQEf62bnnT+1Dkj/iFsKuWm3MBUkjzoPsbDaTe3j4TkMG8XwmUke2G+RgkDV7ywmS2eXBOARdQC5M8H3EBR9qaszlGA+fSPT9R7xQr0HLjj1LqLPfnqVMYHBVgMWu7YOGI=
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - xvfb-run wct
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct -s 'default'; fi"
dist: trusty
